import "normalize.css";
import "./globals.scss";
import style from "./layout.module.scss";
import { font_M_PLUS_1, font_pretended } from "@/fonts/fonts";
import Header from "./(rootLayout)/Header";
import useInitTheme from "./_serverHooks/getInitTheme";
import Footer from "./(rootLayout)/Footer";

export const metadata = {
  title: "2DCJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = useInitTheme();

  return (
    <html lang="ko" data-theme={theme.value}>
      <body className={`${font_M_PLUS_1.className}`}>
        <Header currentTheme={theme.value} />
        <main className={`${font_pretended.className} ${style.page}`}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
