import type { Metadata } from 'next';

import { FunctionComponent, PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface JavascriptLayoutProps extends PropsWithChildren {}

const JavascriptLayout: FunctionComponent<JavascriptLayoutProps> = ({
  children,
}) => {
  return <div>{children}</div>;
};

export default JavascriptLayout;
